FLASH_STRING(FREQ_LABEL, "FREQ: ");
FLASH_STRING(RSSI_LABEL, "RSSI: ");
FLASH_STRING(SNR_LABEL, "SNR: ");
FLASH_STRING(FREQOFF_LABEL, "FREQOFF: ");

FLASH_STRING(ORIGINATOR_LABEL, "Originator: ");
FLASH_STRING(EVENT_LABEL, "Event: ");
FLASH_STRING(LOCATIONS_LABEL, "Locations: ");
FLASH_STRING(LOCATION_CODES_LABEL, "Location Codes: ");
FLASH_STRING(DURATION_LABEL, "Duration: ");
FLASH_STRING(DAY_LABEL, " Day: ");
FLASH_STRING(TIME_LABEL, " Time: ");
FLASH_STRING(CALLSIGN_LABEL, "Callsign: ");

FLASH_STRING(VOLUME_LABEL, "Volume: ");
FLASH_STRING(MUTE_ON_LABEL, "Mute: On\n");
FLASH_STRING(MUTE_OFF_LABEL, "Mute: Off\n");
FLASH_STRING(RADIO_ON_LABEL, "Radio: On\n");
FLASH_STRING(RADIO_OFF_LABEL, "Radio: Off\n");
FLASH_STRING(CHANNEL_UP_LABEL, "Channel Up\n");
FLASH_STRING(CHANNEL_DOWN_LABEL, "Channel Down\n");

FLASH_STRING(WAT_ON_LABEL, "WAT: On\n");
FLASH_STRING(WAT_OFF_LABEL, "WAT: Off\n");

FLASH_STRING(STARTING_SI4707_LABEL, "Starting up the Si4707.......\n\n");
FLASH_STRING(DEFAULTS_SET_LABEL, "Defaults set.\n");
FLASH_STRING(CONFIG_SAVED_LABEL, "Config saved.\n");
FLASH_STRING(SCANNING_LABEL, "Scanning.....\n");
FLASH_STRING(EOM_DETECTED, "EOM detected\n");
FLASH_STRING(ERROR_OCCURRED_LABEL, "An error occured!\n\n");

FLASH_STRING(VERSION_INFO_LABEL, "Version Information\n");
FLASH_STRING(PART_NUMBER_LABEL, "PN: ");
FLASH_STRING(PATCH_HIGH_LABEL, "PatchH: ");
FLASH_STRING(PATCH_LOW_LABEL, "PatchL: ");
FLASH_STRING(CHIP_REVISION_LABEL, "Chip Rev: ");
FLASH_STRING(COMPONENT_MAJOR_LABEL, "CMP Major: ");
FLASH_STRING(COMPONENT_MINOR_LABEL, "CMP Minor: ");
FLASH_STRING(FIRMWARE_MAJOR_LABEL, "FW Major: ");
FLASH_STRING(FIRMWARE_MINOR_LABEL, "FW Minor: ");

FLASH_STRING(MENU, "Display this menu =\t 'h' or '?'\n"
  "Channel down =\t\t 'd'\n"
  "Channel up =\t\t 'u'\n"
  "Scan =\t\t\t 's'\n"
  "Volume + =\t\t '+'\n"
  "Volume - =\t\t '-'\n"
  "Mute / Unmute =\t\t 'm'\n"
  "On / Off =\t\t 'o'\n"
  "Save Settings = \t 'e'\n\n"
);
